/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorefrontRouteImport } from './routes/_storefront'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StorefrontIndexRouteImport } from './routes/_storefront/index'
import { Route as StorefrontAccountRouteImport } from './routes/_storefront/account'
import { Route as StorefrontBestSellersRouteImport } from './routes/_storefront/best-sellers'
import { Route as StorefrontBookAppointmentRouteImport } from './routes/_storefront/book-appointment'
import { Route as StorefrontCartRouteImport } from './routes/_storefront/cart'
import { Route as StorefrontContactRouteImport } from './routes/_storefront/contact'
import { Route as StorefrontFaqRouteImport } from './routes/_storefront/faq'
import { Route as StorefrontFragranceGuideRouteImport } from './routes/_storefront/fragrance-guide'
import { Route as StorefrontGiftsRouteImport } from './routes/_storefront/gifts'
import { Route as StorefrontNewArrivalsRouteImport } from './routes/_storefront/new-arrivals'
import { Route as StorefrontOurStoryRouteImport } from './routes/_storefront/our-story'
import { Route as StorefrontShippingReturnsRouteImport } from './routes/_storefront/shipping-returns'
import { Route as StorefrontShopRouteImport } from './routes/_storefront/shop'
import { Route as StorefrontTermsOfServiceRouteImport } from './routes/_storefront/terms-of-service'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as StorefrontProductIdRouteImport } from './routes/_storefront/product.$id'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers_.new'
import { Route as AdminInventoryNewRouteImport } from './routes/admin/inventory_.new'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders_.new'

const StorefrontRoute = StorefrontRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontAccountRoute = StorefrontAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontBestSellersRoute = StorefrontBestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontBookAppointmentRoute =
  StorefrontBookAppointmentRouteImport.update({
    id: '/book-appointment',
    path: '/book-appointment',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontCartRoute = StorefrontCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontContactRoute = StorefrontContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontFaqRoute = StorefrontFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontFragranceGuideRoute =
  StorefrontFragranceGuideRouteImport.update({
    id: '/fragrance-guide',
    path: '/fragrance-guide',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontGiftsRoute = StorefrontGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontNewArrivalsRoute = StorefrontNewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontOurStoryRoute = StorefrontOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontShippingReturnsRoute =
  StorefrontShippingReturnsRouteImport.update({
    id: '/shipping-returns',
    path: '/shipping-returns',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontShopRoute = StorefrontShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontTermsOfServiceRoute =
  StorefrontTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => StorefrontRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const StorefrontProductIdRoute = StorefrontProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StorefrontRoute,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/customers_/new',
  path: '/customers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryNewRoute = AdminInventoryNewRouteImport.update({
  id: '/inventory_/new',
  path: '/inventory/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StorefrontIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account': typeof StorefrontAccountRoute
  '/best-sellers': typeof StorefrontBestSellersRoute
  '/book-appointment': typeof StorefrontBookAppointmentRoute
  '/cart': typeof StorefrontCartRoute
  '/contact': typeof StorefrontContactRoute
  '/faq': typeof StorefrontFaqRoute
  '/fragrance-guide': typeof StorefrontFragranceGuideRoute
  '/gifts': typeof StorefrontGiftsRoute
  '/new-arrivals': typeof StorefrontNewArrivalsRoute
  '/our-story': typeof StorefrontOurStoryRoute
  '/shipping-returns': typeof StorefrontShippingReturnsRoute
  '/shop': typeof StorefrontShopRoute
  '/terms-of-service': typeof StorefrontTermsOfServiceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$id': typeof StorefrontProductIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account': typeof StorefrontAccountRoute
  '/best-sellers': typeof StorefrontBestSellersRoute
  '/book-appointment': typeof StorefrontBookAppointmentRoute
  '/cart': typeof StorefrontCartRoute
  '/contact': typeof StorefrontContactRoute
  '/faq': typeof StorefrontFaqRoute
  '/fragrance-guide': typeof StorefrontFragranceGuideRoute
  '/gifts': typeof StorefrontGiftsRoute
  '/new-arrivals': typeof StorefrontNewArrivalsRoute
  '/our-story': typeof StorefrontOurStoryRoute
  '/shipping-returns': typeof StorefrontShippingReturnsRoute
  '/shop': typeof StorefrontShopRoute
  '/terms-of-service': typeof StorefrontTermsOfServiceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof StorefrontIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$id': typeof StorefrontProductIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_storefront': typeof StorefrontRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_storefront/account': typeof StorefrontAccountRoute
  '/_storefront/best-sellers': typeof StorefrontBestSellersRoute
  '/_storefront/book-appointment': typeof StorefrontBookAppointmentRoute
  '/_storefront/cart': typeof StorefrontCartRoute
  '/_storefront/contact': typeof StorefrontContactRoute
  '/_storefront/faq': typeof StorefrontFaqRoute
  '/_storefront/fragrance-guide': typeof StorefrontFragranceGuideRoute
  '/_storefront/gifts': typeof StorefrontGiftsRoute
  '/_storefront/new-arrivals': typeof StorefrontNewArrivalsRoute
  '/_storefront/our-story': typeof StorefrontOurStoryRoute
  '/_storefront/shipping-returns': typeof StorefrontShippingReturnsRoute
  '/_storefront/shop': typeof StorefrontShopRoute
  '/_storefront/terms-of-service': typeof StorefrontTermsOfServiceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_storefront/': typeof StorefrontIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_storefront/product/$id': typeof StorefrontProductIdRoute
  '/admin/customers_/new': typeof AdminCustomersNewRoute
  '/admin/inventory_/new': typeof AdminInventoryNewRoute
  '/admin/orders_/new': typeof AdminOrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/account'
    | '/best-sellers'
    | '/book-appointment'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/fragrance-guide'
    | '/gifts'
    | '/new-arrivals'
    | '/our-story'
    | '/shipping-returns'
    | '/shop'
    | '/terms-of-service'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/inquiries'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/'
    | '/product/$id'
    | '/admin/customers/new'
    | '/admin/inventory/new'
    | '/admin/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/account'
    | '/best-sellers'
    | '/book-appointment'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/fragrance-guide'
    | '/gifts'
    | '/new-arrivals'
    | '/our-story'
    | '/shipping-returns'
    | '/shop'
    | '/terms-of-service'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/inquiries'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/product/$id'
    | '/admin/customers/new'
    | '/admin/inventory/new'
    | '/admin/orders/new'
  id:
    | '__root__'
    | '/_storefront'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/_storefront/account'
    | '/_storefront/best-sellers'
    | '/_storefront/book-appointment'
    | '/_storefront/cart'
    | '/_storefront/contact'
    | '/_storefront/faq'
    | '/_storefront/fragrance-guide'
    | '/_storefront/gifts'
    | '/_storefront/new-arrivals'
    | '/_storefront/our-story'
    | '/_storefront/shipping-returns'
    | '/_storefront/shop'
    | '/_storefront/terms-of-service'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/inquiries'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/_storefront/'
    | '/admin/'
    | '/_storefront/product/$id'
    | '/admin/customers_/new'
    | '/admin/inventory_/new'
    | '/admin/orders_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StorefrontRoute: typeof StorefrontRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/account': {
      id: '/_storefront/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StorefrontAccountRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/best-sellers': {
      id: '/_storefront/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof StorefrontBestSellersRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/book-appointment': {
      id: '/_storefront/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof StorefrontBookAppointmentRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/cart': {
      id: '/_storefront/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StorefrontCartRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/contact': {
      id: '/_storefront/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StorefrontContactRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/faq': {
      id: '/_storefront/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StorefrontFaqRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/fragrance-guide': {
      id: '/_storefront/fragrance-guide'
      path: '/fragrance-guide'
      fullPath: '/fragrance-guide'
      preLoaderRoute: typeof StorefrontFragranceGuideRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/gifts': {
      id: '/_storefront/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof StorefrontGiftsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/new-arrivals': {
      id: '/_storefront/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof StorefrontNewArrivalsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/our-story': {
      id: '/_storefront/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof StorefrontOurStoryRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/shipping-returns': {
      id: '/_storefront/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof StorefrontShippingReturnsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/shop': {
      id: '/_storefront/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StorefrontShopRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/terms-of-service': {
      id: '/_storefront/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof StorefrontTermsOfServiceRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/product/$id': {
      id: '/_storefront/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof StorefrontProductIdRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/admin/customers_/new': {
      id: '/admin/customers_/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory_/new': {
      id: '/admin/inventory_/new'
      path: '/inventory/new'
      fullPath: '/admin/inventory/new'
      preLoaderRoute: typeof AdminInventoryNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders_/new': {
      id: '/admin/orders_/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface StorefrontRouteChildren {
  StorefrontAccountRoute: typeof StorefrontAccountRoute
  StorefrontBestSellersRoute: typeof StorefrontBestSellersRoute
  StorefrontBookAppointmentRoute: typeof StorefrontBookAppointmentRoute
  StorefrontCartRoute: typeof StorefrontCartRoute
  StorefrontContactRoute: typeof StorefrontContactRoute
  StorefrontFaqRoute: typeof StorefrontFaqRoute
  StorefrontFragranceGuideRoute: typeof StorefrontFragranceGuideRoute
  StorefrontGiftsRoute: typeof StorefrontGiftsRoute
  StorefrontNewArrivalsRoute: typeof StorefrontNewArrivalsRoute
  StorefrontOurStoryRoute: typeof StorefrontOurStoryRoute
  StorefrontShippingReturnsRoute: typeof StorefrontShippingReturnsRoute
  StorefrontShopRoute: typeof StorefrontShopRoute
  StorefrontTermsOfServiceRoute: typeof StorefrontTermsOfServiceRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontProductIdRoute: typeof StorefrontProductIdRoute
}

const StorefrontRouteChildren: StorefrontRouteChildren = {
  StorefrontAccountRoute: StorefrontAccountRoute,
  StorefrontBestSellersRoute: StorefrontBestSellersRoute,
  StorefrontBookAppointmentRoute: StorefrontBookAppointmentRoute,
  StorefrontCartRoute: StorefrontCartRoute,
  StorefrontContactRoute: StorefrontContactRoute,
  StorefrontFaqRoute: StorefrontFaqRoute,
  StorefrontFragranceGuideRoute: StorefrontFragranceGuideRoute,
  StorefrontGiftsRoute: StorefrontGiftsRoute,
  StorefrontNewArrivalsRoute: StorefrontNewArrivalsRoute,
  StorefrontOurStoryRoute: StorefrontOurStoryRoute,
  StorefrontShippingReturnsRoute: StorefrontShippingReturnsRoute,
  StorefrontShopRoute: StorefrontShopRoute,
  StorefrontTermsOfServiceRoute: StorefrontTermsOfServiceRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontProductIdRoute: StorefrontProductIdRoute,
}

const StorefrontRouteWithChildren = StorefrontRoute._addFileChildren(
  StorefrontRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminInventoryNewRoute: typeof AdminInventoryNewRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminInventoryNewRoute: AdminInventoryNewRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StorefrontRoute: StorefrontRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
